/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
  docs: [
    'index',
    {
      type: 'category',
      label: "Platform",
      link: {
        type: "generated-index",
        title: "Collections",
        description: "Collections of resources for engineering leaders",
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'platform', // Generate sidebar slice from docs/tutorials/easy
        },
      ]
    },
    {
      type: 'category',
      label: "People",
      link: {
        type: "generated-index",
        title: "Collections",
        description: "Collections of resources for engineering leaders",
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'people', // Generate sidebar slice from docs/tutorials/easy
        },
      ]
    },
    {
      type: 'category',
      label: "Projects",
      link: {
        type: "generated-index",
        title: "Collections",
        description: "Collections of resources for engineering leaders",
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'projects', // Generate sidebar slice from docs/tutorials/easy
        },
      ]
    },
    {
      type: 'category',
      label: "Product",
      link: {
        type: "generated-index",
        title: "Collections",
        description: "Collections of resources for engineering leaders",
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'product', // Generate sidebar slice from docs/tutorials/easy
        },
      ]
    }
  ]
};

module.exports = sidebars;
